language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
dist: trusty
sudo: required
node_js:
  - "stable"
  - "10"
  - "9"
stages:
  - |
    setup
    test
    document
    name: deploy
    if: branch = master
    name: release
    if: branch = master
jobs:
  include:
    - stage: setup
      name: install
      script: 
        - npm i -g typescript@latest
        - npm i -g coveralls
    - stage: test
      name: "Run all unit tests"
      script: npm run test:all
      name: "Run smoketests"
      script: npm run smoketest
    - stage: document
      name: "Generate API documents"
      script: npm run docs
    - stage: deploy
      name: "Deploy Github Pages"
      script: echo "Deploying GitHub Pages..."
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
          branch: master
      name: "Deploying Coveralls report"
      script: npm run coverage
    - stage: release
      script: npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
git:
  depth: 3
