name: Build and Test Workflow

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Built and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm run build
          npm run test