name: Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  publish_pages:
    name: Deploys the README to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: "."
          GH_PAT: ${{secrets.GITHUB_TOKEN}}

  release_gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get install wine
      - run: |
          npm install
          npm run build
          npm run dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Upload Mac to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: "dist/SaveThePrincess-0.0.1.dmg"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Windows to Release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: "dist/SaveThePrincess Setup 0.0.1.exe"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
